### ISSUE TITLE
Slides part 1 app registration screenshots are outdated

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-training-restapi#8]
During the next content revision it'd be nice to update the app registration screenshots that are in the first slide deck as this portal has now been retired.
This is not urgent, my hope is that it helps maintainers to know what should be updated during content revision and that it makes their work easier. :)

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this repository and will not be maintaining it going forward. For an updated sample that calls Microsoft Graph from an ASP.NET application, see https://github.com/microsoftgraph/msgraph-training-aspnet-core.
